[package]
name = "Projeto_LP"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"
sha3 = "0.10.8"
base64 = "0.22.1"

